/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as MembersIndexRouteImport } from './routes/members/index'
import { Route as InfluencersIndexRouteImport } from './routes/influencers/index'
import { Route as CouponsIndexRouteImport } from './routes/coupons/index'
import { Route as ProductsNewRouteImport } from './routes/products/new'
import { Route as CouponsNewRouteImport } from './routes/coupons/new'
import { Route as ProductsProductIdEditRouteImport } from './routes/products/$productId.edit'
import { Route as CouponsCouponIdEditRouteImport } from './routes/coupons/$couponId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencersIndexRoute = InfluencersIndexRouteImport.update({
  id: '/influencers/',
  path: '/influencers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsIndexRoute = CouponsIndexRouteImport.update({
  id: '/coupons/',
  path: '/coupons/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsNewRoute = CouponsNewRouteImport.update({
  id: '/coupons/new',
  path: '/coupons/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdEditRoute = ProductsProductIdEditRouteImport.update({
  id: '/products/$productId/edit',
  path: '/products/$productId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsCouponIdEditRoute = CouponsCouponIdEditRouteImport.update({
  id: '/coupons/$couponId/edit',
  path: '/coupons/$couponId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coupons/new': typeof CouponsNewRoute
  '/products/new': typeof ProductsNewRoute
  '/coupons/': typeof CouponsIndexRoute
  '/influencers/': typeof InfluencersIndexRoute
  '/members/': typeof MembersIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/coupons/$couponId/edit': typeof CouponsCouponIdEditRoute
  '/products/$productId/edit': typeof ProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coupons/new': typeof CouponsNewRoute
  '/products/new': typeof ProductsNewRoute
  '/coupons': typeof CouponsIndexRoute
  '/influencers': typeof InfluencersIndexRoute
  '/members': typeof MembersIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/coupons/$couponId/edit': typeof CouponsCouponIdEditRoute
  '/products/$productId/edit': typeof ProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coupons/new': typeof CouponsNewRoute
  '/products/new': typeof ProductsNewRoute
  '/coupons/': typeof CouponsIndexRoute
  '/influencers/': typeof InfluencersIndexRoute
  '/members/': typeof MembersIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/coupons/$couponId/edit': typeof CouponsCouponIdEditRoute
  '/products/$productId/edit': typeof ProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coupons/new'
    | '/products/new'
    | '/coupons/'
    | '/influencers/'
    | '/members/'
    | '/orders/'
    | '/products/'
    | '/settings/'
    | '/coupons/$couponId/edit'
    | '/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coupons/new'
    | '/products/new'
    | '/coupons'
    | '/influencers'
    | '/members'
    | '/orders'
    | '/products'
    | '/settings'
    | '/coupons/$couponId/edit'
    | '/products/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/coupons/new'
    | '/products/new'
    | '/coupons/'
    | '/influencers/'
    | '/members/'
    | '/orders/'
    | '/products/'
    | '/settings/'
    | '/coupons/$couponId/edit'
    | '/products/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CouponsNewRoute: typeof CouponsNewRoute
  ProductsNewRoute: typeof ProductsNewRoute
  CouponsIndexRoute: typeof CouponsIndexRoute
  InfluencersIndexRoute: typeof InfluencersIndexRoute
  MembersIndexRoute: typeof MembersIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  CouponsCouponIdEditRoute: typeof CouponsCouponIdEditRoute
  ProductsProductIdEditRoute: typeof ProductsProductIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencers/': {
      id: '/influencers/'
      path: '/influencers'
      fullPath: '/influencers/'
      preLoaderRoute: typeof InfluencersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons/': {
      id: '/coupons/'
      path: '/coupons'
      fullPath: '/coupons/'
      preLoaderRoute: typeof CouponsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/new': {
      id: '/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons/new': {
      id: '/coupons/new'
      path: '/coupons/new'
      fullPath: '/coupons/new'
      preLoaderRoute: typeof CouponsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId/edit': {
      id: '/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/products/$productId/edit'
      preLoaderRoute: typeof ProductsProductIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons/$couponId/edit': {
      id: '/coupons/$couponId/edit'
      path: '/coupons/$couponId/edit'
      fullPath: '/coupons/$couponId/edit'
      preLoaderRoute: typeof CouponsCouponIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CouponsNewRoute: CouponsNewRoute,
  ProductsNewRoute: ProductsNewRoute,
  CouponsIndexRoute: CouponsIndexRoute,
  InfluencersIndexRoute: InfluencersIndexRoute,
  MembersIndexRoute: MembersIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  CouponsCouponIdEditRoute: CouponsCouponIdEditRoute,
  ProductsProductIdEditRoute: ProductsProductIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
