/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as MypageRouteImport } from './routes/mypage'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PromotionsIndexRouteImport } from './routes/promotions/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as PaymentSuccessRouteImport } from './routes/payment/success'
import { Route as PaymentFailRouteImport } from './routes/payment/fail'
import { Route as PSlugRouteImport } from './routes/p/$slug'
import { Route as CouponCodeRouteImport } from './routes/coupon/$code'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as BoardsBoardSlugIndexRouteImport } from './routes/boards/$boardSlug/index'
import { Route as BoardsBoardSlugNewRouteImport } from './routes/boards/$boardSlug/new'
import { Route as BoardsBoardSlugPostIdRouteImport } from './routes/boards/$boardSlug/$postId'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageRoute = MypageRouteImport.update({
  id: '/mypage',
  path: '/mypage',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsIndexRoute = PromotionsIndexRouteImport.update({
  id: '/promotions/',
  path: '/promotions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailRoute = PaymentFailRouteImport.update({
  id: '/payment/fail',
  path: '/payment/fail',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponCodeRoute = CouponCodeRouteImport.update({
  id: '/coupon/$code',
  path: '/coupon/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsBoardSlugIndexRoute = BoardsBoardSlugIndexRouteImport.update({
  id: '/boards/$boardSlug/',
  path: '/boards/$boardSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsBoardSlugNewRoute = BoardsBoardSlugNewRouteImport.update({
  id: '/boards/$boardSlug/new',
  path: '/boards/$boardSlug/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsBoardSlugPostIdRoute = BoardsBoardSlugPostIdRouteImport.update({
  id: '/boards/$boardSlug/$postId',
  path: '/boards/$boardSlug/$postId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/mypage': typeof MypageRoute
  '/wishlist': typeof WishlistRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/coupon/$code': typeof CouponCodeRoute
  '/p/$slug': typeof PSlugRoute
  '/payment/fail': typeof PaymentFailRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/': typeof ProductsIndexRoute
  '/promotions/': typeof PromotionsIndexRoute
  '/boards/$boardSlug/$postId': typeof BoardsBoardSlugPostIdRoute
  '/boards/$boardSlug/new': typeof BoardsBoardSlugNewRoute
  '/boards/$boardSlug/': typeof BoardsBoardSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/mypage': typeof MypageRoute
  '/wishlist': typeof WishlistRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/coupon/$code': typeof CouponCodeRoute
  '/p/$slug': typeof PSlugRoute
  '/payment/fail': typeof PaymentFailRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products': typeof ProductsIndexRoute
  '/promotions': typeof PromotionsIndexRoute
  '/boards/$boardSlug/$postId': typeof BoardsBoardSlugPostIdRoute
  '/boards/$boardSlug/new': typeof BoardsBoardSlugNewRoute
  '/boards/$boardSlug': typeof BoardsBoardSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/mypage': typeof MypageRoute
  '/wishlist': typeof WishlistRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/coupon/$code': typeof CouponCodeRoute
  '/p/$slug': typeof PSlugRoute
  '/payment/fail': typeof PaymentFailRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/': typeof ProductsIndexRoute
  '/promotions/': typeof PromotionsIndexRoute
  '/boards/$boardSlug/$postId': typeof BoardsBoardSlugPostIdRoute
  '/boards/$boardSlug/new': typeof BoardsBoardSlugNewRoute
  '/boards/$boardSlug/': typeof BoardsBoardSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/mypage'
    | '/wishlist'
    | '/auth/callback'
    | '/coupon/$code'
    | '/p/$slug'
    | '/payment/fail'
    | '/payment/success'
    | '/products/$productId'
    | '/products/'
    | '/promotions/'
    | '/boards/$boardSlug/$postId'
    | '/boards/$boardSlug/new'
    | '/boards/$boardSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/mypage'
    | '/wishlist'
    | '/auth/callback'
    | '/coupon/$code'
    | '/p/$slug'
    | '/payment/fail'
    | '/payment/success'
    | '/products/$productId'
    | '/products'
    | '/promotions'
    | '/boards/$boardSlug/$postId'
    | '/boards/$boardSlug/new'
    | '/boards/$boardSlug'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/mypage'
    | '/wishlist'
    | '/auth/callback'
    | '/coupon/$code'
    | '/p/$slug'
    | '/payment/fail'
    | '/payment/success'
    | '/products/$productId'
    | '/products/'
    | '/promotions/'
    | '/boards/$boardSlug/$postId'
    | '/boards/$boardSlug/new'
    | '/boards/$boardSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  MypageRoute: typeof MypageRoute
  WishlistRoute: typeof WishlistRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CouponCodeRoute: typeof CouponCodeRoute
  PSlugRoute: typeof PSlugRoute
  PaymentFailRoute: typeof PaymentFailRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  PromotionsIndexRoute: typeof PromotionsIndexRoute
  BoardsBoardSlugPostIdRoute: typeof BoardsBoardSlugPostIdRoute
  BoardsBoardSlugNewRoute: typeof BoardsBoardSlugNewRoute
  BoardsBoardSlugIndexRoute: typeof BoardsBoardSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage': {
      id: '/mypage'
      path: '/mypage'
      fullPath: '/mypage'
      preLoaderRoute: typeof MypageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions/': {
      id: '/promotions/'
      path: '/promotions'
      fullPath: '/promotions/'
      preLoaderRoute: typeof PromotionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/fail': {
      id: '/payment/fail'
      path: '/payment/fail'
      fullPath: '/payment/fail'
      preLoaderRoute: typeof PaymentFailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupon/$code': {
      id: '/coupon/$code'
      path: '/coupon/$code'
      fullPath: '/coupon/$code'
      preLoaderRoute: typeof CouponCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$boardSlug/': {
      id: '/boards/$boardSlug/'
      path: '/boards/$boardSlug'
      fullPath: '/boards/$boardSlug/'
      preLoaderRoute: typeof BoardsBoardSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$boardSlug/new': {
      id: '/boards/$boardSlug/new'
      path: '/boards/$boardSlug/new'
      fullPath: '/boards/$boardSlug/new'
      preLoaderRoute: typeof BoardsBoardSlugNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$boardSlug/$postId': {
      id: '/boards/$boardSlug/$postId'
      path: '/boards/$boardSlug/$postId'
      fullPath: '/boards/$boardSlug/$postId'
      preLoaderRoute: typeof BoardsBoardSlugPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  MypageRoute: MypageRoute,
  WishlistRoute: WishlistRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CouponCodeRoute: CouponCodeRoute,
  PSlugRoute: PSlugRoute,
  PaymentFailRoute: PaymentFailRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  PromotionsIndexRoute: PromotionsIndexRoute,
  BoardsBoardSlugPostIdRoute: BoardsBoardSlugPostIdRoute,
  BoardsBoardSlugNewRoute: BoardsBoardSlugNewRoute,
  BoardsBoardSlugIndexRoute: BoardsBoardSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
